INFO: loading config from /etc/shadowwords.json
Traceback (most recent call last):
  File "/usr/bin/sslocal", line 9, in <module>
    load_entry_point('shadowsocks==2.1.0', 'console_scripts', 'sslocal')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/local.py", line 44, in main
    config = utils.get_config(True)
  File "/usr/lib/python2.7/dist-packages/shadowsocks/utils.py", line 103, in get_config
    with open(config_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/etc/shadowwords.json'
INFO: loading config from /etc/shadowwords.json
Traceback (most recent call last):
  File "/usr/bin/sslocal", line 9, in <module>
    load_entry_point('shadowsocks==2.1.0', 'console_scripts', 'sslocal')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/local.py", line 44, in main
    config = utils.get_config(True)
  File "/usr/lib/python2.7/dist-packages/shadowsocks/utils.py", line 103, in get_config
    with open(config_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/etc/shadowwords.json'
INFO: loading config from /etc/shadowwords.json
Traceback (most recent call last):
  File "/usr/bin/sslocal", line 9, in <module>
    load_entry_point('shadowsocks==2.1.0', 'console_scripts', 'sslocal')()
  File "/usr/lib/python2.7/dist-packages/shadowsocks/local.py", line 44, in main
    config = utils.get_config(True)
  File "/usr/lib/python2.7/dist-packages/shadowsocks/utils.py", line 103, in get_config
    with open(config_path, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/etc/shadowwords.json'
